### ISSUE TITLE
Ideas for beginner projects

### ISSUE THREAD

**Issue by tamouse** [railsmn/railsmn.github.io#10]
* The Blog, http://guides.rubyonrails.org/getting_started.html
* Twitter Clone, https://www.railstutorial.org/book/toy_app#cha-a_toy_app
* Using Google Maps API to localizing posts
* Turn your blog into a multi-user blog
* Blog aggregator
* Storefront for you Dog Biscuit Company

**Comment by tamouse** [comment]
* simulate an ATM
* your friend's band website, with back end for posting tour dates, updates to dicsography, band photos, band blogs, and a contact / mailing list sign up for fans
* simulate an elevator
* make a copy of the IMDB: films, genres, actors, directors. Produce a list of films an actor was in. Product a list of Romantic Comedies Liam Neesan has been in.
* make a family tree where each person can enter their own info (for fun, get your family to use it). Make it secure by having users sign up to enter info.

**Comment by tamouse** [comment]
Do the above, and make them pretty, responsive, and fast.

**Comment by Bentonian** [comment]
Cool! Does this go on a "learning rails" page on Rails.mn?

**Comment by tamouse** [comment]
@Bentonian  -- yes, I am removing the opencamp, and making a list of these instead. Feel free to add more!

**Comment by tamouse** [comment]
* build a photo gallery
* build a Pinterest clone
