### ISSUE TITLE
RailsMN content re-org

### ISSUE THREAD

**Issue by jaw6** [railsmn/railsmn.github.io#2]
* [x] - #1 
* [x] - point rails.mn to railsmn.github.io ? (@derekrockwell)
* [x] - Links to other presentations
* [x] - Remove old sessions docs, pointer to new site
* [x] - invite others to join RailsMN org, hack on the new site

**Comment by tamouse** [comment]
https://github.com/railsmn/railsmn.github.io/pull/14
